apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.homelabz.eu/library/cks-backend
    newTag: 1886fbf9572594403e26bc922bfabec58c491100

patches:
  - patch: |-
      - op: replace
        path: /spec/hosts/0
        value: "api.cks.homelabz.eu"
    target:
      kind: VirtualService
      name: cks-backend
  - patch: |-
      - op: remove
        path: /spec/strategy/blueGreen/prePromotionAnalysis
    target:
      kind: Rollout
      name: cks-backend
  - patch: |-
      - op: remove
        path: /spec/strategy/blueGreen/postPromotionAnalysis
    target:
      kind: Rollout
      name: cks-backend
  - patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: "prod"
      - op: replace
        path: /data/LOG_LEVEL
        value: "DEBUG"
    target:
      kind: ConfigMap
      name: cks-backend
configMapGenerator:
  - name: cks-backend-config
    behavior: merge
    envs:
      - configmap
