apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../ephemeral-base

images:
  - name: registry.homelabz.eu/library/cks-backend
    newTag: pr-will-be-replaced

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: "dev.api.cks.homelabz.eu"
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "dev.api.cks.homelabz.eu"
      - op: replace
        path: /spec/rules/0/host
        value: "dev.api.cks.homelabz.eu"
    target:
      kind: Ingress
      name: cks-backend

configMapGenerator:
  - name: cks-backend-config
    behavior: merge
    envs:
      - configmap
