apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.toolz.homelabz.eu/library/cks-backend
    newTag: 7aeebaf26c3d80e7cfddf32acc08d908b096916a

configMapGenerator:
  - name: cks-backend-config
    behavior: merge
    envs:
      - configmap
