apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.toolz.homelabz.eu/library/cks-backend
    newTag: 3a4aab50b744d6c150f0b2dd64b702dece004c74

configMapGenerator:
  - name: cks-backend-config
    behavior: merge
    envs:
      - configmap
