apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.toolz.homelabz.eu/library/cks-backend
    newTag: 803453c3a1b871559740a3ccfd74e19a3cfd55d8

configMapGenerator:
  - name: cks-backend-config
    behavior: merge
    envs:
      - configmap
